name: Build And Run Test

run-name: ${{ github.actor }} is building and testing app
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, release-*]

jobs:
  My-Job-Name:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.6
        # Provide the password for postgres
        env:
          POSTGRES_DB: ace_the_exam
          POSTGRES_USER: acetheexam
          POSTGRES_PASSWORD: acetheexam
        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          # Maps tcp port 5432 on service container to the host
#          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11.7'
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        env:
          E2E_DB_URL: postgres://acetheexam:acetheexam@db:5432/ace_the_exam
        run: |
          python manage.py test
          python manage.py check
